task:
  map_number: "17"
  round: 1
  data_name: "fixed_train_data_20260316_172943"
  method: "gen_legend_ratio_augmentation"
  train_model_method: "3_18_EVA_02_22m"

paths:
  in_roots:
    - "/data/ch21908234/work/SAM_Classifier_Feedback_Loop/run_seg_cls_loop_result/sam1/tile_split_method/3_18_EVA_02_22m/17/round_1"
  output_root: "/data/ch21908234/work/SAM_Classifier_Feedback_Loop/run_seg_cls_loop_result/classify/tile_split_method/SAM_post_classify_out"
  ckpt_path: "/data/ch21908234/work/SAM_Classifier_Feedback_Loop/model/gen_legend_ratio_augmentation/17/fixed_train_data_20260316_172943/best_model.pth"

model:
  model_name: "eva02_small_patch14_336.mim_in22k_ft_in1k"
  patch_h: 56
  patch_w: 98
  stride_h: 56
  stride_w: 98
  batch_size: 128
  conf_th: 0.30
  use_cuda_if_available: true

normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

vote:
  majority_th: 1.0
  min_patch: 5
  min_nonblank: 2
  strong_min: 1

blank_rule:
  white_bgr: [255, 255, 255]
  blank_name: "blank"
  blank_white_area_ratio: 0.5
  small_threshold_extra_w: 60

names:
  dirname_mid: "mid"

  dirname_correct: "segmentation_verified"
  dirname_merged: "merged"
  dirname_error: "segmentation_rejected"
  dirname_error_postmerge_tmp: "segmentation_rejected__postmerge_tmp"

  error_csv_name: "errors.csv"
  skipped_csv_name: "skipped.csv"

  merged_canvas_filename_template: "{core}_full.png"
  error_image_filename_template: "{map_name}_ty{ty}_tx{tx}_{mid_name}"
  composite_small_filename_template: "{map_name}_ty{ty}_tx{tx}_composite_small.png"
  source_desc_template: "{map_name}/round_{round}_ty{ty}_tx{tx}_{mid_name}_core={core}"

regex:
  tile_glob_pattern: "tile_*_*"
  tile_dir_regex: 'tile_(\d+)_([-\d]+)$'
  tile_coord_regex: '(?:^|_)ty(-?\d+)_tx(-?\d+)(?:_|$)'

csv:
  error_csv_header:
    - "map"
    - "tile_y"
    - "tile_x"
    - "mid_file"
    - "status"
    - "assigned_core"
    - "strong_cnt"
    - "weak_cnt"
    - "top_core_counts"
    - "reason"

  skipped_csv_header:
    - "map"
    - "tile_y"
    - "tile_x"
    - "mid_file"
    - "reason"
    - "covered_by"